apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
spec:
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: hostpath
      volumeMode: Filesystem
    status:
      phase: Pending
