---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
spec:
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: hostpath
        resources:
          requests:
            storage: 5Gi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager
      port: web
