apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- service-monitors.yaml
- service-monitor-kubelet.yaml
- pod-monitors.yaml
- probes.yaml
- prometheus-rbac.yaml
- prometheus-rules.yaml
- prometheus.yaml
- service.yaml

configurations:
  - env-var-transformer.yaml
