---
#apiVersion: monitoring.coreos.com/v1
#kind: PodMonitor
#metadata:
#  name: prometheus
#  namespace: default
#  labels:
#    team: mon
#spec:
#  podMetricsEndpoints:
#  - port: web
#  namespaceSelector:
#    matchNames:
#      - monitoring
#  selector:
#    matchLabels:
#      prometheus: minikube
