apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: promtail

resources:
- rbac.yaml
- daemonset.yaml
- service.yaml

#secretGenerator:
#- name: promtail-config
#  behavior: create
#  files: 
#    - configs/promtail.yaml

configMapGenerator:
- name: promtail-config
  behavior: create
  files: 
    - configs/promtail.yaml

configurations:
  - env-var-transformer.yaml
