apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: blackbox-exporter

resources:
- rbac.yaml
#- podsecurity.yaml
- blackbox-config.yaml
- deployment.yaml
- service.yaml
