---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
spec:
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: static-scrape-configs.yaml
  additionalAlertManagerConfigs:
    name: additional-am-configs
    key: static-am-configs.yaml
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager
      port: web
