apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- alertmanager.yaml
- service.yaml

secretGenerator:
- name: alertmanager-main
  behavior: create
  files:
  - configs/alertmanager.yaml
  options:
    disableNameSuffixHash: true
