global:
route:
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 20s # global alertmanager has 15s which cause that in case everything is OK alerts came from there
  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 30s
  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 1h
  group_by: [ prometheus, alertname, severity ]
  receiver: "null"
  routes:
    - receiver: "slack"
      match_re:
        severity: critical|warning
      continue: false
    - receiver: "null"
      match_re:
        severity: none
      continue: true
receivers:
  - name: "null"
  - name: "slack"
    slack_configs:
    - send_resolved: true
      http_config:
        follow_redirects: true
      api_url: https://hooks.slack.com/services/xxx
