{
 "title": "GD-mon-stack: Test dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "K8s memory total (Gb)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_bytes / 1000000000"
    }
   ]
  },
  {
   "title": "# K8s cluster cpus",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Memory idle by cluster",
   "type": "timeseries",
   "description": "https://sysdig.com/blog/prometheus-query-examples/",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum((container_memory_usage_bytes{container!=\"POD\",container!=\"\"} - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"memory\"})) * -1 >0 ) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "CPU idle by cluster",
   "type": "timeseries",
   "description": "https://sysdig.com/blog/prometheus-query-examples/",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[10m]) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\"})) * -1 >0)"
    }
   ]
  }
 ]
}