apiVersion: v1
data:
  alertmanager.yaml: |-
    apiVersion: 1
    datasources:
    - name: Alertmanager
      uid: GDMONSTACK
      type: alertmanager
      typeName: Alertmanager
      access: proxy
      url: alertmanager.$(NAMESPACE):9093
      jsonData:
        implementation: prometheus
      editable: true
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      isDefault: true
      access: proxy
      url: http://prometheus.$(NAMESPACE):9090
      version: 1
      editable: true
      jsonData:
        alertmanagerUid: GDMONSTACK
  loki.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.$(NAMESPACE):3100
      editable: true
      jsonData:
        alertmanagerUid: GDMONSTACK
        maxLines: 5000
        timeout: "60"
kind: ConfigMap
metadata:
  labels:
    app: grafana
    grafana_datasource: "1"
  name: grafana-datasources
  namespace: default
