apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- rbac.yaml
- grafana-datasources.yaml
- grafana-dashboards.yaml
- grafana-config.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
- name: grafana-dashboard-sources
  behavior: create
  files: 
    - dashboards/description.json
    - dashboards/example.json
  options:
    labels:
      grafana_dashboard: "1"

configurations:
  - env-var-transformer.yaml
