---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gd-mon-stack
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gd-mon-stack
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gd-mon-stack
roleRef:
  kind: ClusterRole
  name: gd-mon-stack
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gd-mon-stack
  namespace: default
