apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ./loki
- ./promtail
- ./kube-state-metrics
- ./node-exporter
- ./blackbox-exporter
- ./pushgateway
- ./prometheus
- ./alertmanager
- ./grafana

generatorOptions:
  disableNameSuffixHash: false
  labels:
    type: gd-mon-stack-generated
  annotations:
    note: generated

configMapGenerator:
- name: environment-variables
  envs:
    - environment-properties.env
  behavior: create

vars:
- name: NAMESPACE
  objref:
    kind: ConfigMap
    name: environment-variables
    apiVersion: v1
  fieldref:
    fieldpath: data.NAMESPACE
