{
 "title": "MON: Alertmanager",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Last succesful alertmanager reload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_config_last_reload_success_timestamp_seconds * 1000"
    }
   ]
  },
  {
   "title": "# active alerts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"active\"}"
    }
   ]
  },
  {
   "title": "# suppressed alerts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"suppressed\"}"
    }
   ]
  },
  {
   "title": "Failed slack notification over 1m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by(integration)(increase(alertmanager_notifications_failed_total{namespace=\"monitoring\",pod=\"alertmanager-main-0\",integration=~\"slack|pagerduty|email\"}[1m]))"
    }
   ]
  },
  {
   "title": "Alerts by state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(alertmanager_alerts) by (state)"
    }
   ]
  },
  {
   "title": "Alertmanager re-loads log records",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{namespace=\"monitoring\",pod=\"alertmanager-main-0\"} |= \"Reload triggered\""
    }
   ]
  }
 ]
}