apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: loki

resources:
#- podsecuritypolicy.yaml
- rbac.yaml
- loki-config.yaml
- loki-rules-config.yaml
- services.yaml
- statefulset.yaml
