---
# Source: loki/templates/configmap-alert.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alerting-rules
  namespace: default
data:
  loki-alerting-rules.yaml: |-
    groups:
      - name: example
        rules:
        - alert: HighThroughputLogStreams
          labels:
            severity: critical
          expr: sum by(namespace)(rate({stream=~"stdout|stderr"}[1m])) > 10
          for: 2m
