{
 "title": "GD monitoring stack: Test dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "K8s cluster CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores)" }
   ]
  },
  {
   "title": "# of PODs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_info)"
    }
   ]
  },
  {
   "title": "# PODs not ready",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_info{created_by_kind!=\"Job\"} AND ON (pod, namespace) kube_pod_status_ready{condition=\"true\"} == 0)"
    }
   ]
  },
  {
   "title": "K8s mem total (Gb)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes) / 1000000000"
    }
   ]
  },
  {
   "title": "Memory idle by cluster",
   "type": "timeseries",
   "description": "https://sysdig.com/blog/prometheus-query-examples/",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum((container_memory_usage_bytes{container!=\"POD\",container!=\"\"} - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"memory\"})) * -1 >0 ) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "CPU idle by cluster",
   "type": "timeseries",
   "description": "https://sysdig.com/blog/prometheus-query-examples/",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[10m]) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\"})) * -1 >0)"
    }
   ]
  },
  {
   "title": "Kubernetes err logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{stream=~\"stderr|stdout\"} |= \"level=error\" !=\"level=info\""
    }
   ]
  }
 ]
}